apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api-image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: mysql-primary.db.svc.cluster.local
        - name: MYSQL_USER
          value: api
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: iplog